server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: fx-deals-warehouse

  datasource:
    url: jdbc:postgresql://localhost:5432/fx_deals_warehouse
    username: fx_user
    password: fx_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true

logging:
  level:
    com.progresssoft.fxdeals: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/fx-deals-warehouse.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always