server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: fx-deals-warehouse

  datasource:
    url: jdbc:postgresql://localhost:5432/fx_deals_warehouse
    username: fx_user
    password: fx_pass123
    driver-class-name: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

